Add support for hypothetically hiding existing indexes in EXPLAIN output.
HypoPG/hypopg pull request #78
Opened 2023-03-13 12:25 UTC by nutVI

- `hypopg_hide_index(oid)`, save the index OID in the backend list, causing EXPLAIN to ignore it.
- `hypopg_unhide_index(oid)`, delete the OID from the backend list, and then the index will be recovered.
- `hypopg_unhide_all_index()`, recover all hidden indexes.
- `hypopg_hidden_indices()`, to get a result set of all hidden index OIDs. 
- `hypopg_hidden_indexes` is a view that provides a result set similar to the pg_indexes system catalog.

This function has been tested in PostgreSQL-12.5, especially during the index test of the TPC-H and TPC-DS data sets(because I recently need it). The final result is that it can be used normally, which is very convenient when judging whether to delete the index.

2023-03-13 14:32 UTC, rjuju requested changes
Hi,

Thanks a lot for the PR!

First round of review, I mostly focused on coding style and nitpicking for now.  Note that this patch doesn't compile:

```
hypopg_index.c:1741:71: error: too many arguments to function call, expected 2, have 3
                rel->indexlist = list_delete_cell(rel->indexlist, lc, prev);
```

I'm assuming that you need to remove ", prev" here.

Some other general comments:

- there should be regression tests for this new features, including hiding real index(es), hypothetical index(es), trying to hide a non-index oid (e.g. a table oid).
- the "micro" version should only be used for bug fixes.  A new feature requires a minor version bump, so this patch should introduce version 1.4.0
- a single commit for everything would be better
- please add your name (or GH nickname if you don't want to disclose your name) to the contributors file :)

2023-03-13 14:32 UTC, rjuju commented on README.md
> +    joynut=# create index on hypo(id);
nitpicking, but could you change the example to use the same db name (rjuju) as the previous examples?  I'm afraid it could lead to confusion

2023-03-13 14:32 UTC, rjuju commented on README.md
> +Continuing with the above case, you can `hide existing index`. Create two real indexes and use `EXPLAIN`:
I think it should say "hide existing indexes" (plural)

Also, the rest of the steps assumes that you actually removed the previously created hypothetical index.  This should be explicitly demonstrated.

2023-03-13 14:32 UTC, rjuju commented on README.md
> +You can use `hypopg_hidden_indices()` to see hidden index oid or use view `hypopg_hidden_indexes`:
the function should be named `hypopg_hidden_indixes` not `hypopg_hidden_indices`

2023-03-13 14:32 UTC, rjuju commented on README.md
> +    f        | public     | hypo      | hypo_id_idx     |  509623
I'm not sure why this should display an index that's not hidden?  It should just be a direct view of the underlying hash table.

2023-03-13 14:32 UTC, rjuju commented on hypopg--1.3.2.sql
> +        (
I think we could avoid that many line breaks.  Also the double quotes aren't necessary, so something like

```
CREATE FUNCTION hypopg_hidden_indices()
    RETURNS TABLE (indexid oid)
    LANGUAGE C
[...]
```

2023-03-13 14:32 UTC, rjuju commented on hypopg--1.3.2.sql
> +CREATE VIEW hypopg_hidden_indexes
As mentioned above this view should display what's stored in the hash table, with extra information from other catalogs, but not info about all indexes in the database.  In any case, having a SELECT in the SELECT clause should be avoided.

2023-03-13 14:32 UTC, rjuju commented on hypopg.c
> +            hypo_hideExistingIndex(rel);
a better name would be `hypo_hideIndexes`, as it can have impact on more than one index at a time, and since it can also hide hypothetical indexes I think.

2023-03-13 14:32 UTC, rjuju commented on hypopg.c
> +            hypo_hideExistingIndex(rel);
nitpicking, but could you preserve the same coding style?  That means using tabs instead of space for indentation, and having an empty line between variable declaration and the rest of the function body (for later code).

2023-03-13 14:32 UTC, rjuju commented on hypopg_index.c
> +List	   *hideIndexes;
I'm not a fan of this name.  I'd prefer to keep "hypo" as a prefix, to make sure it doesn't interfere with any other code.  Maybe "hypoHiddenIndexes" ?

2023-03-13 14:32 UTC, rjuju commented on hypopg_index.c
> +static bool hypo_recover_index(Oid indexid);
The current practice in nearby code is to use similar name but switching the "index" position.  So hypopg_hide_index underlying C function should be `hypo_index_hide`

2023-03-13 14:32 UTC, rjuju commented on hypopg_index.c
> + * add index oid to the hideIndexes if no exist
Nitpicking but the comment should be a sentence, so the first word should start with a capital letter and it should and with a ".".

Other than that, the function should check that the given oid is an existing index (possibly hypothetical), not blindly accept any given value.

2023-03-13 14:32 UTC, rjuju commented on hypopg_index.c
> +    foreach(lc, hideIndexes)
Not need to code it yourself you can use `list_member_int` provided function.

2023-03-13 14:32 UTC, rjuju commented on hypopg_index.c
> +	while ((lc = list_head(hideIndexes)) != NULL)
For removing all hidden indexes we should just call `list_free()` and then set the pointer to NIL.

2023-03-13 14:32 UTC, rjuju commented on hypopg_index.c
> +                // if lc is list_head, prev's still eqaul NULL
Please use `/* xxx */` comment style rather than `//`.  Also typo in "eqaul"

2023-03-14 06:40 UTC, nutVI commented on README.md
> +    joynut=# create index on hypo(id);
Thanks for the review. I will refer to your questions and suggestions to make modifications.

What I am most concerned about is actually compatibility issues. I downloaded the source code of `pg-15.1` and confirmed that `list_delete_cell` has two parameters in this version, while `pg-12.5` requires three. So I may change it to `list_delete_ptr` later, which should be more compatible.

I have always been impressed by the compatibility of hypopg. I have seen that the source code contains various `#if PG_VERSION_NUM` to ensure version compatibility. However, my dev-env only has `pg-12.5`, so I can only use code that is as version compatible as possible.

Currently, my testing method is to compile and run in a `pg-12.5` environment to see if it is stable. It is indeed difficult for me to set up test environments for all other versions. So I also want to ask if there is a better way to test version compatibility.

2023-03-14 06:53 UTC, rjuju commented on README.md
> +    joynut=# create index on hypo(id);
I think you should consider working with current postgres HEAD (so 16devel) to be compatible with the newest upstream API.  I will be happy to take care of any required backward compatbility fixes as I can still compile all versions down to 9.2 easily (and I actually already have all those available on my local dev box for easy validation), but if you prefer also take care of it feel free to take the time you need to do so.

You're right that `list_delete_cell` signature changed, and that's something that I actually wanted to work on as as far as I can see the current call to `list_delete_ptr` is buggy.  You can look at [upstream commit 1cff1b95ab6](https://github.com/postgres/postgres/commit/1cff1b95ab6) for more details about the infrastructure change.  Given that the code is currently broken you can simply blindly use the 2-arguments version of list_delete_cell and I will take care in another commit of switching that to the new API and making compatibility macros if possible (which seems unlikely), or just use for loops with necessary var rather than using foreach if not.

2023-03-15 01:39 UTC, rjuju commented on README.md
> +    joynut=# create index on hypo(id);
After a 2nd look the current list_delete_ptr call is actually ok.

Also, I don't see a way to have the same approach for all versions if you need iterate over a list and remove some entries.  So for your PR you have rely on foreach / foreach_delete_current(), and any compat code will have to use a different looping approach using #if PG_VERSION_NUM blocks.

2023-03-15 15:56 UTC, nutVI commented on hypopg.c
> +            hypo_hideExistingIndex(rel);
Oh,  I just realized that I missed this conversation because it was folded. It may take some time for me to submit a PR that addresses the issue of `hiding hypothetical indexes`.

2023-03-16 03:44 UTC, rjuju requested changes

2023-03-16 03:44 UTC, rjuju commented on hypopg.c
> +            hypo_hideExistingIndex(rel);
But your code would already hide hypothetical indexes, as in get_relation_info there's no difference between a real index and a hypothetical one.  The only thing to adapt is to check that the given oid is either an existing index **or an existing hypothetical index** when calling hypopg_hide_index(), you could even rely on hypo_get_index() for that.

2023-03-16 03:44 UTC, rjuju commented on expected/hypo_hide_index.out
> + (12659,<12659>btree_hypo_id_val)
you can't rely on stable oid output in regression tests.  You can look at other tests on how to make sure that it works without failing in case of different oid (ie. using COUNT(*) FROM hypopg_create_index())

2023-03-17 06:33 UTC, rjuju requested changes
Thanks for the updated patch!

It's getting close to being ready.  On top of those comments, 2 things:

- the doc (in docs/) needs to be modified for this new feature
- I think it would be better to have the change from 1.3.2 to 1.4.0 done in an separate and prior commit to make this commit cleaner.  I can take care of that if you want.

2023-03-17 06:33 UTC, rjuju commented on include/hypopg_index.h
> +#define HIDDEN_INDEX_COLS	    1   /* # of column hypopg_hidden_indices()
thinko when renaming the underlying function to hypopg_hidden_indexes()

2023-03-17 06:33 UTC, rjuju commented on hypopg--1.4.0.sql
> +    UNION
nitpicking: we know that both sets are disjoint so using UNION ALL here avoids to try to uselessly deduplicate rows

2023-03-17 06:33 UTC, rjuju commented on hypopg--1.4.0.sql
> +    SELECT i.oid     AS indexrelid,
I think it would be good to add a column to explicitly say whether the given index is hypothetical or not.  You can usually guess based on the name but it doesn't cost much to make it explicit.

2023-03-17 06:33 UTC, rjuju commented on hypopg--1.4.0.sql
> +             LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
why do you need LEFT JOIN for those 2 relations?

2023-03-17 06:33 UTC, rjuju commented on hypopg--1.4.0.sql
> +         hypopg_hidden_indexes() hi
please use an explicit JOIN construct here too.

2023-03-17 06:33 UTC, rjuju commented on hypopg_index.c
> +static bool hypo_index_unhide(Oid indexid);
nitpicking but could you move this prototype declaration after hypo_index_remove(), to keep it more or less in alphabetical order?

2023-03-17 06:33 UTC, rjuju commented on hypopg_index.c
> +	hypo_index_unhide(indexid);
good thinking.  Could you cover this case in the regression tests too?

While at it, maybe change the comment to "remove this index from the list of hidden indexes if present".

2023-03-17 06:33 UTC, rjuju commented on hypopg_index.c
> +	if(!is_hypo)
nitpicking: missing space between if and ( here and some other places

2023-03-17 06:33 UTC, rjuju commented on hypopg_index.c
> + * Unhide the oid to restore this index on EXPLAIN.
A better comment would be "Unhide the given index oid (hypothetical or not) to make it visible to the planner again." (here and the underlying function)

2023-03-17 06:33 UTC, rjuju commented on hypopg_index.c
> +List	   *hypoHiddenIndexes;
it should be explicitly initialized to NIL in _PG_init(), next to hypoIndexes initialization.

2023-03-17 06:33 UTC, rjuju commented on hypopg_index.c
> + * Add index oid to the hypoHiddenIndexes if no exist.
Maybe
> Add the given oid for the list of hidden indexes if it's a valid index (hypothetical or not), and if not hidden already.  Return true if the oid is added to the list, false otherwise.

2023-03-17 06:33 UTC, rjuju commented on hypopg_index.c
> +			hypoHiddenIndexes = list_delete_oid(hypoHiddenIndexes, index_oid);
It's a bit sad to call list_delete_oid, as this function will iterate against the list a second time.  Since the function doesn't really tell us whether something was removed or not, we could just compare the `list_length()` before and after to return the information, and avoid iterating over the list explicitly?

2023-03-17 06:33 UTC, rjuju commented on hypopg_index.c
> +					rel->indexlist = list_delete_ptr(rel->indexlist, index);
with recent code you now have to use foreach_delete_current()

2023-03-17 06:33 UTC, rjuju commented on hypopg_index.c
> +					/* check rel->indexlist once again to prevent the same oid. */
I'm not sure what this comment means, but I'm wondering if it's because you're not using foreach_delete_current()?  You shouldn't need this do loop

2023-03-17 06:33 UTC, rjuju commented on Makefile
> +REGRESS      = hypopg hypo_hide_index
I'd prefer to have this test moved last, could you add if around like 53, after the possible addition of hypo_hash?

2023-03-17 06:33 UTC, rjuju commented on README.md
> +Continuing with the above case, you can `hide existing indexes`,
nitpicking: there are a lot of trailing whitespaces, could you remove them?

note that you need to keep those in the expected/*.sql file.

2023-03-17 11:04 UTC, nutVI commented on hypopg_index.c
> +					/* check rel->indexlist once again to prevent the same oid. */
> I'm not sure what this comment means

I cannot be sure whether there might be duplicate index OIDs in `rel->indexlist`, so I chose to repeatedly delete the index to ensure its removal.

> but I'm wondering if it's because you're not using foreach_delete_current()? You shouldn't need this do loop

Based on this assumption and considering older versions such as pg-12.5, I opted to use a do-while() loop for the repeated deletion, which happens to be compatible with pg-16devel. If it is clear that such a situation cannot occur, I can remove the do-while() structure but still use list_delete_ptr() to remove and then break.

2023-03-17 11:11 UTC, nutVI commented on hypopg_index.c
> +	hypo_index_unhide(indexid);
> good thinking. Could you cover this case in the regression tests too?

There is already a `hypopg_drop_index` related regression tests at line 63 of `test/sql/hypo_hide_index.sql`. But perhaps I should also add a test for `hypopg_reset`?

2023-03-17 13:25 UTC, nutVI commented
> * I think it would be better to have the change from 1.3.2 to 1.4.0 done in an separate and prior commit to make this commit cleaner.  I can take care of that if you want.

I'm a bit confused about "an separate and prior commit". Should I continue to try to merge my PR into a single commit, and what does `prior` mean? As you may have seen, I've been using `-force` to ensure a single commit, and I'm not sure if that's a problem, but it does make the Git history clearer.

2023-03-17 14:12 UTC, rjuju commented on hypopg_index.c
> +	hypo_index_unhide(indexid);
oh indeed, sorry I missed it.  Perfect then!

After a bit of thought I think that hypo_index_reset() will eventually be rewritten to be more efficient now that everything is allocated in a dedicated memory context (added in version 1.1.3), so having an explicit test for hypopg_reset() when there's a hidden hypothetical index might be a good idea, to make sure that we don't leave any random dead pointer somewhere.

2023-03-17 14:12 UTC, rjuju commented on hypopg_index.c
> +					/* check rel->indexlist once again to prevent the same oid. */
> I cannot be sure whether there might be duplicate index OIDs in rel->indexlist, so I chose to repeatedly delete the index to ensure its removal.

I don't think you can have duplicate there, I will double check just in case.

> Based on this assumption and considering older versions such as pg-12.5, I opted to use a do-while() loop for the repeated deletion, which happens to be compatible with pg-16devel

unfortunately this isn't really compatible with pg12+.  Per foreach_delete_current comment, it's the only legal way for delete an element from an active foreach loop:
```
 * foreach_delete_current -
 *	  delete the current list element from the List associated with a
 *	  surrounding foreach() loop, returning the new List pointer.
 *
 * This is equivalent to list_delete_cell(), but it also adjusts the foreach
 * loop's state so that no list elements will be missed.  Do not delete
 * elements from an active foreach loop's list in any other way!
 */
#define foreach_delete_current(lst, cell)	\
[...]
```

a backward compatibility will have to be done, but I think it will need to be two different chunks of code.

2023-03-17 14:18 UTC, rjuju commented
> > * I think it would be better to have the change from 1.3.2 to 1.4.0 done in an separate and prior commit to make this commit cleaner.  I can take care of that if you want.
> 
> I'm a bit confused about "an separate and prior commit". Should I continue to try to merge my PR into a single commit, and what does `prior` mean? As you may have seen, I've been using `-force` to ensure a single commit, and I'm not sure if that's a problem, but it does make the Git history clearer.

Sorry if that was unclear.  What I meant was to split your current commit in 2 commits:
1. one commit that just tweak stuff to have the current version be 1.4.0 rather than 1.3.2 (rename the files, change the .control).  See for instance commit 30c4f2a52c74da44f8ce1b28b764260c91cdb7ab (start working on version X.Y.Z)
2. one commit with everything else

And yes I see you've been squashing things in the same commit and doing push force, that's perfect!  You could work with multiple fixup commits added to the PR if you prefer (I'm fine with both approach), but eventually they would need to be squashed to a single commit (well 2 with the version bump) before merging.

2023-03-17 14:42 UTC, nutVI commented on hypopg_index.c
> +					/* check rel->indexlist once again to prevent the same oid. */
> a backward compatibility will have to be done, but I think it will need to be two different chunks of code.

I think your insistence is right. The source code structure of the old and new list is too different, and using code that is compatible with both types of versions will confuse people who read the code in the future. Later, I will switch to using `foreach_delete_current`.

I found that the source code update of the list seems to be in the pg-13.0 version, and I will isolate it using `#if PG_VERSION_NUM < 130000`. Can you help me confirm if it is pg-13.0?

2023-03-18 00:36 UTC, rjuju commented on hypopg_index.c
> +					/* check rel->indexlist once again to prevent the same oid. */
I confirm:

```
$ git branch --contains 1cff1b95ab6 | grep REL
+ REL_13_STABLE
+ REL_14_STABLE
+ REL_15_STABLE
```

2023-03-19 12:01 UTC, rjuju commented
Thanks for the updated patchset!  I had a quick look and overall it looks good to me (minus some minor details, but I can fix that afterward).  I will look at it thoroughly next week, trying to build the docs and run regression tests over all major versions, and hopefully merge the PR.

2023-03-20 03:29 UTC, rjuju commented
The 1.4.0 preparation is not ok:

```
 hypopg--1.3.1--1.3.2.sql => hypopg--1.3.2--1.4.0.sql |  0
 hypopg--1.3.2.sql                                    | 62 ----------------------------------------------------
 hypopg--1.3.1.sql => hypopg--1.4.0.sql               |  0
 hypopg.control                                       |  2 +-
```

The latest released version was 1.3.1, and we want to have the next version be 1.4.0.  So what you should have done is:

- rename 1.3.1--1.3.2.sql to 1.3.1--1.4.0.sql
- keep 1.3.1.sql (I always keep the last 2 version scripts)
- rename 1.3.2.sql to 1.4.0.sql

and the next commit should add more stuff to both 1.4.0.sql and 1.3.1--1.4.00sql

As is you removed all the unreleased work since version 1.3.1.

I can take care of this part if you prefer.

2023-03-21 03:03 UTC, rjuju requested changes

2023-03-21 03:03 UTC, rjuju commented on test/sql/hypo_hide_index.sql
> +SELECT hypopg_hide_index('hypo0'::regclass);
this one can be removed, the error happens before the function is called so it's not adding any coverage.  Same for the unhide function.

2023-03-21 03:03 UTC, rjuju commented on include/hypopg_index.h
> +#define HIDDEN_INDEX_COLS		1   /* # of column hypopg_hidden_indexes()
the HYPO_ prefix is missing

2023-03-21 03:03 UTC, rjuju commented on hypopg--1.4.0.sql
> +
all of this should also be present in the 1.3.1--1.4.0.sql file, otherwise people upgrading from 1.3.1 (or older) won't have the new function.  You can manually try it using:

```sql
DROP EXTENSION IF EXISTS hypopg;
CREATE EXTENSION hypopg VERSION '1.3.1';
ALTER EXTENSION hypopg UPDATE;
\dx+ hypopg
```

2023-03-21 03:03 UTC, rjuju commented on hypopg_index.c
> +			lc = lc == NULL ? list_head(rel->indexlist) : lnext(lc);
you should use the same approach as the rest of the upstream postgres code in older version, ie. using a "next" variable and assigning ls in the "for" construct.

See for instance https://github.com/postgres/postgres/blob/REL_12_STABLE/src/backend/commands/tsearchcmds.c#L584-L594 for a simple example.

2023-03-21 05:10 UTC, nutVI commented on hypopg_index.c
> +			lc = lc == NULL ? list_head(rel->indexlist) : lnext(lc);
Oh, elegant writing. Thanks for the review: ), sorry about that I checked the source code roughly, but didn't notice this example. This way of writing is really intuitive and doesn't require any comments.

2023-03-23 08:49 UTC, rjuju approved these changes
It all looks good to me!

2023-03-23 08:49 UTC, merged

2023-03-23 08:50 UTC, rjuju commented
After the last round of change I think it's good enough to be merged, I will work on some follow up commits to fix minor stylistic things.

Thanks a lot for writing this feature!

2023-03-23 09:12 UTC, nutVI commented
I am very happy to have opportunity to participate this feature! Thanks your patient review, I also learned a lot. :)